// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const MISSING_SUPABASE_MESSAGE =
  'Supabase is not connected yet. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in Lovable Cloud or your local .env file.';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getSupabaseConfig() {
  const url = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || '';
  const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || '';

  return { url, key };
}

function createFallbackError() {
  return new Error(MISSING_SUPABASE_MESSAGE);
}

function createFallbackQueryBuilder() {
  const fail = async () => ({ data: null, error: createFallbackError() });
  const chain: any = {
    select: fail,
    insert: fail,
    update: fail,
    upsert: fail,
    delete: fail,
    eq: () => chain,
    order: () => chain,
    match: () => chain,
    limit: () => chain,
    maybeSingle: fail,
    single: fail,
  };
  return chain;
}

function createFallbackClient() {
  const auth = {
    async getSession() {
      return { data: { session: null }, error: null };
    },
    onAuthStateChange() {
      return {
        data: {
          subscription: {
            unsubscribe() {},
          },
        },
      };
    },
    async signInWithPassword() {
      return { data: { user: null, session: null }, error: createFallbackError() };
    },
    async signUp() {
      return { data: { user: null, session: null }, error: createFallbackError() };
    },
    async signInWithOtp() {
      return { data: {}, error: createFallbackError() };
    },
    async verifyOtp() {
      return { data: { user: null, session: null }, error: createFallbackError() };
    },
    async signOut() {
      return { error: null };
    },
  };

  const storage = {
    from() {
      return {
        getPublicUrl: () => ({ data: { publicUrl: '' }, error: null }),
      };
    },
  };

  const from = () => createFallbackQueryBuilder();

  return { auth, storage, from };
}

function createSupabaseClient() {
  const { url, key } = getSupabaseConfig();

  if (!url || !key) {
    console.warn(`[Supabase] ${MISSING_SUPABASE_MESSAGE}`);
    return createFallbackClient() as any;
  }

  console.log('🚀 Supabase Client Initialized with URL:', url);

  return createClient<Database>(url, key, {
    global: {
      fetch: createSupabaseFetch(key),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

